#pragma once

#define UNKNOWN_MG_PER_DL -1
#define UNKNOWN_PROPANE_LEVEL -1
#define UNKNOWN_TEMPERATURE -100.0

#define DATA_COLLECTOR
#define ENABLE_DISPLAY

#define ENABLE_SYNC_SENDER
#define ENABLE_SYNC_RECEIVER
#if defined(ENABLE_SYNC_SENDER) || defined(ENABLE_SYNC_RECEIVER)
#define ENABLE_SYNC
#endif
